"""new Schedule table

Revision ID: 95e8e2709aeb
Revises: dc7b456fc514
Create Date: 2023-05-05 20:52:01.810109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e8e2709aeb'
down_revision = 'dc7b456fc514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('veiaco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['veiaco_id'], ['veiaco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
